name: secomp_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "public/secomp_icone.png" # Caminho da sua imagem
  background_color: "#FFFFFF"     # Fundo branco
  adaptive_icon_background: "#FFFFFF" # Necessário para Android 8.0+
  adaptive_icon_foreground: "public/secomp_icone.png" # A logo por cima do fundo

flutter_native_splash:
  color: "#E6E6E6"
  # Para "remover" o ícone no Android 12, use a mesma cor do fundo no ícone
  android_12:
    color: "#E6E6E6"
    icon_color: "#E6E6E6" # Isso faz o ícone ficar invisível (mesma cor do fundo)

  fullscreen: true
  android: true
  ios: true
flutter:
  assets:
    - public/
    - assets/images/
  uses-material-design: true

